export const myTasksMock = [
  {
    id: 1,
    title: 'Aktywność Fizyczna',
    comment: '',
    prior: 'high',
    category: 'zdrowie',
  },
  {
    id: 2,
    title: 'Poranna Rutyna',
    comment: 'Picie kawy , ogarnięcie, afirmacje ect',
    prior: 'wysoki',
    category: 'życie',
  },
  {
    id: 3,
    title: 'Praca',
    comment: '',
    prior: 'wysoki',
    category: 'rozwój',
  },
  {
    id: 4,
    title: 'Przygotowanie do wyjścia',
    comment: '',
    prior: 'średni',
    category: 'życie',
  },
  {
    id: 5,
    title: 'Spotkania towarzyskie',
    comment: '',
    prior: 'średni',
    category: 'relacje',
  },
  {
    id: 6,
    title: 'Zakupy',
    comment: '',
    prior: 'wysoki',
    category: 'życie',
  },
  {
    id: 7,
    title: 'Dom',
    comment: 'sprzatanie, gotowanie ect',
    prior: 'średni',
    category: 'życie',
  },
  {
    id: 8,
    title: 'Wycieczki',
    comment: '',
    prior: 'średni',
    category: 'hobbi',
  },
  {
    id: 9,
    title: 'Czas z rodziną',
    comment: '',
    prior: 'wysoki',
    category: 'relacje',
  },
  {
    id: 10,
    title: 'Kroki',
    comment: '',
    prior: 'wysoki',
    category: 'zdrowie',
  },
]

export const timeRecordsMock = [
  {
    durationInHour: '4',
    durationInMinutes: '12',
    tasksHour: [6, 7, 8],
    workDate: '2023-04-03',
    workDescription: 'develop my own project',
    id: 1,
  },
  {
    durationInHour: '2',
    durationInMinutes: '12',
    workDate: '2023-04-03',
    tasksHour: [11, 12, 13],
    workDescription: 'Cooking lunch',
    id: 2,
  },
  {
    durationInHour: '1',
    durationInMinutes: '12',
    workDate: '2023-04-04',
    tasksHour: [11, 12, 13],
    workDescription: 'lunch',
    id: 3,
  },
  {
    durationInHour: '1',
    durationInMinutes: '12',
    workDate: '2023-04-04',
    tasksHour: [16, 17, 18],
    workDescription: 'Cooking lunch',
    id: 4,
  },
]
